end_game = {
    "end",
    "quit",
    "exit",
    "stop",
    "leave",
    "finish",
    "done",
    "end game",
    "endgame",
    "end_game",
    "end it",
    "endit",
    "end_it",
    "end the game",
    "endthegame",
    "end_the_game",
    "end this game",
    "endthisgame",
    "end_this_game",
    "end this",
    "endthis",
    "end_this",
    "end it now",
    "enditnow",
    "end_it_now",
    "end the game now",
    "endthegamenow",
    "end_the_game_now",
    "end this game now",
    "endthisgamenow",
    "end_this_game_now",
    "end this now",
    "endthisnow",
    "end_this_now",
    "end it right now",
    "enditrightnow",
    "end_it_right_now",
    "end the game right now",
    "endthegamerightnow",
    "end_the_game_right_now",
    "end this game right now",
    "endthisgamerightnow",
    "end_this_game_right_now",
    "end this right now",
    "endthisrightnow",
    "end_this_right_now",
    "end it immediately",
    "enditimmediately",
    "end_it_immediately",
    "end the game immediately",
    "endthegameimmediately",
    "end_the_game_immediately",
    "end this game immediately",
    "endthisgameimmediately",
    "end_this_game_immediately",
    "end this immediately",
    "endthisimmediately",
    "end_this_immediately",
}
